imports:
  - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

parameters:
  sylius_core.public_dir: '%kernel.project_dir%/public'

sylius_addressing:
  resources:
    address:
      classes:
        model: App\Entity\Shop\Addressing\Address
    country:
      classes:
        model: App\Entity\Shop\Addressing\Country
    province:
      classes:
        model: App\Entity\Shop\Addressing\Province
    zone:
      classes:
        model: App\Entity\Shop\Addressing\Zone
    zone_member:
      classes:
        model: App\Entity\Shop\Addressing\ZoneMember

sylius_attribute:
  resources:
    product:
      attribute:
        classes:
          model: App\Entity\Shop\Product\ProductAttribute
        translation:
          classes:
            model: App\Entity\Shop\Product\ProductAttributeTranslation
      attribute_value:
        classes:
          model: App\Entity\Shop\Product\ProductAttributeValue

sylius_channel:
  resources:
    channel:
      classes:
        model: App\Entity\Shop\Channel\Channel
sylius_core:
  resources:
    product_image:
      classes:
        model: App\Entity\Shop\Product\ProductImage
    taxon_image:
      classes:
        model: App\Entity\Shop\Taxonomy\TaxonImage
    product_taxon:
      classes:
        model: App\Entity\Shop\Product\ProductTaxon
    channel_pricing:
      classes:
        model: App\Entity\Shop\Channel\ChannelPricing

sylius_currency:
  resources:
    currency:
      classes:
        model: App\Entity\Shop\Currency\Currency
    exchange_rate:
      classes:
        model: App\Entity\Shop\Currency\ExchangeRate

sylius_customer:
  resources:
    customer:
      classes:
        model: App\Entity\Shop\Customer\Customer
    customer_group:
      classes:
        model: App\Entity\Shop\Customer\CustomerGroup

sylius_locale:
  resources:
    locale:
      classes:
        model: App\Entity\Shop\Locale\Locale

sylius_order:
  resources:
    order:
      classes:
        model: App\Entity\Shop\Order\Order
    order_item:
      classes:
        model: App\Entity\Shop\Order\OrderItem
    order_item_unit:
      classes:
        model: App\Entity\Shop\Order\OrderItemUnit
    adjustment:
      classes:
        model: App\Entity\Shop\Order\Adjustment
    order_sequence:
      classes:
        model: App\Entity\Shop\Order\OrderSequence

sylius_payment:
  resources:
    payment_method:
      classes:
        model: App\Entity\Shop\Payment\PaymentMethod
      translation:
        classes:
          model: App\Entity\Shop\Payment\PaymentMethodTranslation
    payment:
      classes:
        model: App\Entity\Shop\Payment\Payment

sylius_payum:
  resources:
    payment_security_token:
      classes:
        model: App\Entity\Shop\Payment\PaymentSecurityToken
    gateway_config:
      classes:
        model: App\Entity\Shop\Payment\GatewayConfig

sylius_product:
  resources:
    product:
      classes:
        model: App\Entity\Shop\Product\Product
      translation:
        classes:
          model: App\Entity\Shop\Product\ProductTranslation
    product_variant:
      classes:
        model: App\Entity\Shop\Product\ProductVariant
      translation:
        classes:
          model: App\Entity\Shop\Product\ProductVariantTranslation
    product_option:
      classes:
        model: App\Entity\Shop\Product\ProductOption
      translation:
        classes:
          model: App\Entity\Shop\Product\ProductOptionTranslation
    product_option_value:
      classes:
        model: App\Entity\Shop\Product\ProductOptionValue
      translation:
        classes:
          model: App\Entity\Shop\Product\ProductOptionValueTranslation
    product_association:
      classes:
        model: App\Entity\Shop\Product\ProductAssociation
    product_association_type:
      classes:
        model: App\Entity\Shop\Product\ProductAssociationType
      translation:
        classes:
          model: App\Entity\Shop\Product\ProductAssociationTypeTranslation

sylius_promotion:
  resources:
    promotion:
      classes:
        model: App\Entity\Shop\Promotion\Promotion
    promotion_rule:
      classes:
        model: App\Entity\Shop\Promotion\PromotionRule
    promotion_action:
      classes:
        model: App\Entity\Shop\Promotion\PromotionAction
    promotion_coupon:
      classes:
        model: App\Entity\Shop\Promotion\PromotionCoupon

sylius_review:
  resources:
    product:
      review:
        classes:
          model: App\Entity\Shop\Product\ProductReview

sylius_shipping:
  resources:
    shipment:
      classes:
        model: App\Entity\Shop\Shipping\Shipment
    shipping_method:
      classes:
        model: App\Entity\Shop\Shipping\ShippingMethod
      translation:
        classes:
          model: App\Entity\Shop\Shipping\ShippingMethodTranslation
    shipping_category:
      classes:
        model: App\Entity\Shop\Shipping\ShippingCategory

sylius_taxation:
  resources:
    tax_category:
      classes:
        model: App\Entity\Shop\Taxation\TaxCategory
    tax_rate:
      classes:
        model: App\Entity\Shop\Taxation\TaxRate

sylius_taxonomy:
  resources:
    taxon:
      classes:
        model: App\Entity\Shop\Taxonomy\Taxon
      translation:
        classes:
          model: App\Entity\Shop\Taxonomy\TaxonTranslation

sylius_user:
  resources:
    admin:
      user:
        classes:
          model: App\Entity\Shop\User\AdminUser
    shop:
      user:
        classes:
          model: App\Entity\Shop\User\ShopUser
    oauth:
      user:
        classes:
          model: App\Entity\Shop\User\UserOAuth

sylius_theme:
  sources:
    filesystem:
      scan_depth: 1
      directories:
        - "%kernel.project_dir%/themes"
