doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            easy_media_type: Adeliom\EasyMediaBundle\Types\EasyMediaType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            EasySeoBundle:
              type: annotation
              alias: Adeliom\EasySeoBundle
              prefix: Adeliom\EasySeoBundle\Entity
              dir: "Entity"
            EasyBlockBundle:
              type: annotation # or attribute
              alias: Adeliom\EasyBlockBundle
              prefix: Adeliom\EasyBlockBundle\Entity
              dir: "Entity"
            EasyBlogBundle:
              type: annotation # or attribute
              alias: Adeliom\EasyBlogBundle
              prefix: Adeliom\EasyBlogBundle\Entity
              dir: "Entity"
            EasyMediaBundle:
              type: annotation # or attribute
              alias: Adeliom\EasyMediaBundle
              prefix: Adeliom\EasyMediaBundle\Entity
              dir: "Entity"
