easy_menu:
  menu:
    class: App\Entity\Menu\Menu
    repository: App\Repository\Menu\MenuRepository
    crud: App\Controller\Admin\Menu\MenuCrudController
  menu_item:
    class: App\Entity\Menu\MenuItem
    repository: App\Repository\Menu\MenuItemRepository
    crud: App\Controller\Admin\Menu\MenuItemCrudController
