twig:
  form_themes:
    - '@EasyMedia/form/easy-media.html.twig'

easy_media:
  storage_name: uploads.storage
  base_url: 'http://localhost:53791/demo/media/download'
  #lock_entity: App\Entity\EasyMedia\Lock
  #metas_entity: App\Entity\EasyMedia\Metas
  media_entity: App\Entity\EasyMedia\Media
  folder_entity: App\Entity\EasyMedia\Folder
