security:
    encoders:
        Adeliom\EasyAdminUserBundle\Entity\User: argon2i
        Sylius\Component\User\Model\UserInterface: argon2i

    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        easy_admin_user_provider:
            id: easy_admin_user.user_provider

        easy_shop_user_provider:
            id: sylius.shop_user_provider.email_or_name_based

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        image_resolver:
            pattern: ^/media/cache/resolve
            security: false

        admin:
            lazy: true
            pattern: ^/admin
            provider: easy_admin_user_provider
            custom_authenticator: easy_admin_user.authenticator
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
            remember_me:
                secret: "%env(APP_SECRET)%"
                name: ADMIN_REMEMBER_ME
                lifetime: 31536000
                path: /admin
                remember_me_parameter: _admin_remember_me
            logout:
                path: easy_admin_logout
                target: easy_admin_login

        shop:
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
            context: shop
            pattern: "%sylius.security.shop_regex%"
            provider: easy_shop_user_provider
            form_login:
                success_handler: sylius.authentication.success_handler
                failure_handler: sylius.authentication.failure_handler
                provider: easy_shop_user_provider
                login_path: easy_shop_login
                check_path: easy_shop_login_check
                failure_path: easy_shop_login
                default_target_path: sylius_shop_homepage
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%env(APP_SECRET)%"
                name: APP_SHOP_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: easy_shop_logout
                target: easy_shop_login
                invalidate_session: false

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/logout, roles: PUBLIC_ACCESS }
        - { path: ^/admin/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

        - { path: "%sylius.security.shop_regex%", role: PUBLIC_ACCESS }
        - { path: "%sylius.security.shop_regex%/_partial", role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [ 127.0.0.1, ::1 ] }
        - { path: "%sylius.security.shop_regex%/_partial", role: ROLE_NO_ACCESS }
        - { path: "%sylius.security.shop_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%sylius.security.shop_regex%/register", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%sylius.security.shop_regex%/verify", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%sylius.security.shop_regex%/account", role: ROLE_USER }
        - { path: ^/, role: PUBLIC_ACCESS }
