security:
    password_hashers:
        Adeliom\EasyAdminUserBundle\Entity\User: argon2i

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_API_ACCESS ]
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_API_ACCESS: ~

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        easy_admin_user_provider:
            id: easy_admin_user.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        image_resolver:
            pattern: ^/media/cache/resolve
            security: false

#        admin:
#            lazy: true
#            pattern: ^/admin
#            provider: easy_admin_user_provider
#            custom_authenticator: easy_admin_user.authenticator
#            # https://symfony.com/doc/current/security/impersonating_user.html
#            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
#            remember_me:
#                secret: "%env(APP_SECRET)%"
#                name: ADMIN_REMEMBER_ME
#                lifetime: 31536000
#                path: /admin
#                remember_me_parameter: _admin_remember_me
#            logout:
#                path: easy_admin_logout
#                target: easy_admin_login

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
#        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
#        - { path: ^/admin/logout, roles: PUBLIC_ACCESS }
#        - { path: ^/admin/reset-password, roles: PUBLIC_ACCESS }
#        - { path: ^/admin, roles: ROLE_ADMIN }

        - { path: ^/, role: PUBLIC_ACCESS }
