name: easyadmin-sandbox
recipe: lamp
config:
  php: 8.1
  composer_version: 2
  database: mariadb
  webroot: public

keys:
  - id_rsa
  - JeromeEngelnAdeliom-GitHub

services:
  appserver:
    build_as_root:
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  minio:
    type: compose
    app_mount: false
    ssl: true
    moreHttpPorts: ['9001', '9000']
    services:
      user: root
      image: minio/minio
      command: /usr/bin/docker-entrypoint.sh minio server --console-address ":9001" /data
      ports:
        - '9000'
        - '9001'
      environment:
        MINIO_ROOT_USER: root
        MINIO_ROOT_PASSWORD: password
        MINIO_BROWSER_REDIRECT_URL: https://minio-easyadmin.lndo.site
        LANDO_NO_USER_PERMS: 1
        LANDO_NO_SCRIPTS: 1

  create_bucket:
    type: compose
    app_mount: false
    scanner: false
    services:
      image: minio/mc
      depends_on:
        - minio
      command: >
        /bin/sh -c "
        mc alias set easyadmin http://minio:9000 root password;
        mc mb --region=fr-par --ignore-existing easyadmin/demo;
        mc anonymous set download easyadmin/demo;
        exit 0;
        "
tooling:
  npm:
    service: appserver
  node:
    service: appserver
  npx:
    service: appserver

  phpcs:
    service: appserver
  phpcbf:
    service: appserver
  php-cs-fixer:
    service: appserver
  phpinsights:
    service: appserver
  phpstan:
    service: appserver
  phpunit:
    service: appserver

  lint-back:
    cmd:
      - appserver: php bin/console lint:container
      - appserver: vendor/bin/php-cs-fixer fix --ansi --diff
      - appserver: composer validate

  console:
    service: appserver
    cwd: bin

