name: easyadmin-sandbox
recipe: lamp
config:
  php: 8.1
  composer_version: 2
  database: mariadb
  webroot: public

keys:
  - id_rsa
  - JeromeEngelnAdeliom-GitHub

services:
  appserver:
    build_as_root:
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

tooling:
  npm:
    service: appserver
  node:
    service: appserver
  npx:
    service: appserver

  phpcs:
    service: appserver
  phpcbf:
    service: appserver
  php-cs-fixer:
    service: appserver
  phpinsights:
    service: appserver
  phpstan:
    service: appserver
  phpunit:
    service: appserver

  lint-back:
    cmd:
      - appserver: php bin/console lint:container
      - appserver: vendor/bin/php-cs-fixer fix --ansi --diff
      - appserver: composer validate

  console:
    service: appserver
    cwd: bin

