<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    Adeliom\EasyAdminUserBundle\EasyAdminUserBundle::class => ['all' => true],
    SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
    FOS\CKEditorBundle\FOSCKEditorBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Presta\SitemapBundle\PrestaSitemapBundle::class => ['all' => true],
    BabDev\PagerfantaBundle\BabDevPagerfantaBundle::class => ['all' => true],
    Adeliom\EasyBlockBundle\EasyBlockBundle::class => ['all' => true],
    Adeliom\EasyBlogBundle\EasyBlogBundle::class => ['all' => true],
    Adeliom\EasyCommonBundle\EasyCommonBundle::class => ['all' => true],
    Adeliom\EasyEditorBundle\EasyEditorBundle::class => ['all' => true],
    Adeliom\EasyFieldsBundle\EasyFieldsBundle::class => ['all' => true],
    Adeliom\EasyMediaBundle\EasyMediaBundle::class => ['all' => true],
    Adeliom\EasyPageBundle\EasyPageBundle::class => ['all' => true],
    Adeliom\EasySeoBundle\EasySeoBundle::class => ['all' => true],
    Adeliom\EasyFaqBundle\EasyFaqBundle::class => ['all' => true],
    Adeliom\EasyMenuBundle\EasyMenuBundle::class => ['all' => true],
    Adeliom\EasyConfigBundle\EasyConfigBundle::class => ['all' => true],
    Adeliom\EasyRedirectBundle\EasyRedirectBundle::class => ['all' => true]
];
